# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15l-bgrzoWer_bIepSpJLz-UAUNoupCvf
"""

import untitled3 as object
print("las suma es: ", object.sumar(6, 7))
print("el numero es: ", object.es_par_impar(1))

object.saludar("Juan")

print(object.area_circulo(5))

print("Los grados fahrenheit son : ",object.celcius_a_fahrenheit(5))

print("los numeros del cuadrado son : ",object.numero_cuadrado(8))

print("el factorial es: ",object.factorial(5))

print("el numero de vocales que tienen solo es: ",object.vocales_palabra("Juan"))

print("la tabla del 8 es : ",object.tabla_multiplicar(8))